# - Find mysql
#
# -*- cmake -*-
#
# Find the native MySQL includes and library
#
#  MySQL_INCLUDE_DIR - where to find mysql.h, etc.
#  MySQL_PLUGIN_DIR
#  MySQL_FOUND       - True if MySQL found.

IF (MySQL_INCLUDE_DIR AND MySQL_LIBRARIES)
  # Already in cache, be silent
  SET(MySQL_FIND_QUIETLY TRUE)
ENDIF (MySQL_INCLUDE_DIR AND MySQL_LIBRARIES)

# Include dir
FIND_PATH(MySQL_INCLUDE_DIR 
  NAMES mysql.h
  PATH_SUFFIXES mysql
)

FIND_PROGRAM(MySQL_CONFIG mysql_config /usr/bin/)
IF(NOT MySQL_CONFIG)
	MESSAGE( FATAL_ERROR "mysql_config NOT found!" )
ENDIF(NOT MySQL_CONFIG)

EXECUTE_PROCESS(COMMAND ${MySQL_CONFIG} --plugindir OUTPUT_VARIABLE MySQL_PLUGIN_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)

IF (MySQL_INCLUDE_DIR AND MySQL_PLUGIN_DIR)
  SET(MySQL_FOUND TRUE)
ELSE (MySQL_INCLUDE_DIR AND MySQL_PLUGIN_DIR)
  SET(MySQL_FOUND FALSE)
ENDIF (MySQL_INCLUDE_DIR AND MySQL_PLUGIN_DIR)

# handle the QUIETLY and REQUIRED arguments and set MySQL_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MySQL DEFAULT_MSG MySQL_PLUGIN_DIR MySQL_INCLUDE_DIR)

MARK_AS_ADVANCED(
  MySQL_INCLUDE_DIR
  MySQL_PLUGIN_DIR
)
